array (
  0 => 
  array (
    'zid' => '796',
    'upzid' => '0',
    'utype' => '0',
    'power' => '2',
    'domain' => 'aa.wamsg.cn',
    'domain2' => '',
    'user' => 'yejianboqqqq',
    'pwd' => 'yejianbo',
    'email' => NULL,
    'phone' => NULL,
    'qq_openid' => '',
    'nickname' => NULL,
    'faceimg' => NULL,
    'rmb' => '1462.29',
    'rmbtc' => '1462.29',
    'point' => '0',
    'pay_type' => '0',
    'pay_account' => '5656@ee.bb',
    'pay_name' => '更好发',
    'qq' => '188988850',
    'sitename' => '58全民易站',
    'title' => '创业项目基地',
    'keywords' => '互联网创业项目',
    'description' => '专注移动互联网创业赚钱实战项目，不定期分享项目实战、项目思维、案例，带你一起走向致富之路。平台提供百万价值的实战培训资料，精准引流爆粉实战，实操网络知识项目，分享流量变现的实操方法与技巧',
    'kfqq' => '188988850',
    'kfwx' => '188988850',
    'anounce' => '',
    'bottom' => '',
    'modal' => '',
    'alert' => '',
    'price' => NULL,
    'iprice' => NULL,
    'appurl' => '/?mod=app&id=2',
    'class' => NULL,
    'ktfz_price' => '10.00',
    'ktfz_price2' => '88.00',
    'ktfz_domain' => '',
    'addtime' => '2022-10-15 06:04:52',
    'lasttime' => '2024-01-27 20:56:18',
    'endtime' => '9999-10-15 00:00:00',
    'template' => NULL,
    'msgread' => NULL,
    'status' => '1',
    'wx_openid' => '',
  ),
  1 => 
  array (
  ),
)